[project]
name = "mcp-server"
version = "0.1.0"
description = "simple mcp server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.9.4",
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]
